### ISSUE TITLE
Weird stuff happening after having way too many servers for the screen

### ISSUE THREAD

**Issue by vloddot** [vloddot/jolt#20]
So if you have way too many servers for the screen, the expected behavior is for it to scroll normally, but a few issues happen:
- The tooltip goes down to the bottom of the screen.
- You can scroll downwards more, leaving the main content at the top.

[Recording of this in action](https://autumn.revolt.chat/attachments/nyYHKAu1coWdhq-PuX_qo46-v2_K13iMnHyxGT0TUo?width=720)

Another subtle yet very obvious issue is the fact that the tooltip isn't perfectly positioned.

I could not replicate this myself but another issue I found was two tooltips appearing at the same time after fiddling with the tooltips a bit. Definitely worth looking into.

**Comment by Gersonzao** [comment]
- openSUSE Leap 15.5
- Xorg
- 0.2.10 AppImage

(I will try reproducing it in new releases and update this)

Please assign this issue to me, since I recorded the video and want to keep an eye on this issue.

Apparently this only happens when the client window isn't tall enough to show all servers in the server list

Here's a better video:
https://github.com/vloddot/jolt/assets/85644671/6aa07a9e-83be-470a-85f1-a558273338e2

**Comment by vloddot** [comment]
I think I already have a fix. I can't test it though. Can you edit the `body` CSS in `src/index.css` to this and test it on your machine?

```css
body {
    @apply bg-gray-700 text-white overflow-hidden;
}
```

**Comment by Gersonzao** [comment]
No longer reproducible on 0.2.11

**Comment by vloddot** [comment]
Great. Issue closed.
